"""add source and recipient fields

Revision ID: 896420808a0b
Revises: d44029bc4885
Create Date: 2026-09-30 00:24:21.125082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '896420808a0b'
down_revision: Union[str, Sequence[str], None] = 'd44029bc4885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_measures', sa.Column('recipient_description', sa.Text(), nullable=True, comment='Подробное текстовое описание получателей'))
    op.add_column('support_measures', sa.Column('source_name', sa.String(length=100), nullable=True, comment='Название источника (МСП.РФ, ФРП, Минсельхоз)'))
    op.add_column('support_measures', sa.Column('source_url', sa.String(), nullable=True, comment='Прямая ссылка на официальную страницу меры'))
    op.alter_column('support_measures', 'id',
               existing_type=sa.VARCHAR(),
               comment='Внутренний ID',
               existing_comment='Внутренний ID меры поддержки',
               existing_nullable=False)
    op.alter_column('support_measures', 'id_form',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='ID формы предоставления (0 если универсальная)',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::character varying"))
    op.alter_column('support_measures', 'active',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='1 - активна, 0 - убрать с платформы',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('support_measures', 'name',
               existing_type=sa.VARCHAR(length=150),
               comment=None,
               existing_comment='Наименование без формулировок НПА',
               existing_nullable=False)
    op.alter_column('support_measures', 'preview',
               existing_type=sa.VARCHAR(length=250),
               comment=None,
               existing_comment='Краткий анонс для списка',
               existing_nullable=True)
    op.alter_column('support_measures', 'short_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Краткое описание для карточки',
               existing_nullable=True)
    op.alter_column('support_measures', 'full_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Полное описание (с HTML тегами)',
               existing_nullable=True)
    op.alter_column('support_measures', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата начала приема заявок (ISO 8601)',
               existing_nullable=True)
    op.alter_column('support_measures', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата окончания приема заявок (ISO 8601)',
               existing_nullable=True)
    op.alter_column('support_measures', 'support_type',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Форма поддержки (ID из справочника)',
               existing_nullable=True)
    op.alter_column('support_measures', 'support_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Лимит оказания меры на заявителя',
               existing_nullable=True)
    op.alter_column('support_measures', 'support_amount_from',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Размер поддержки ОТ (руб)',
               existing_nullable=True)
    op.alter_column('support_measures', 'support_amount_till',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Размер поддержки ДО (руб)',
               existing_nullable=True)
    op.alter_column('support_measures', 'recipient_category',
               existing_type=sa.VARCHAR(),
               comment='micro, small, medium',
               existing_comment='Категории: micro, small, medium, other (массив)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('support_measures', 'recipient_category',
               existing_type=sa.VARCHAR(),
               comment='Категории: micro, small, medium, other (массив)',
               existing_comment='micro, small, medium',
               existing_nullable=True)
    op.alter_column('support_measures', 'support_amount_till',
               existing_type=sa.INTEGER(),
               comment='Размер поддержки ДО (руб)',
               existing_nullable=True)
    op.alter_column('support_measures', 'support_amount_from',
               existing_type=sa.INTEGER(),
               comment='Размер поддержки ОТ (руб)',
               existing_nullable=True)
    op.alter_column('support_measures', 'support_count',
               existing_type=sa.INTEGER(),
               comment='Лимит оказания меры на заявителя',
               existing_nullable=True)
    op.alter_column('support_measures', 'support_type',
               existing_type=sa.INTEGER(),
               comment='Форма поддержки (ID из справочника)',
               existing_nullable=True)
    op.alter_column('support_measures', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата окончания приема заявок (ISO 8601)',
               existing_nullable=True)
    op.alter_column('support_measures', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата начала приема заявок (ISO 8601)',
               existing_nullable=True)
    op.alter_column('support_measures', 'full_description',
               existing_type=sa.TEXT(),
               comment='Полное описание (с HTML тегами)',
               existing_nullable=True)
    op.alter_column('support_measures', 'short_description',
               existing_type=sa.TEXT(),
               comment='Краткое описание для карточки',
               existing_nullable=True)
    op.alter_column('support_measures', 'preview',
               existing_type=sa.VARCHAR(length=250),
               comment='Краткий анонс для списка',
               existing_nullable=True)
    op.alter_column('support_measures', 'name',
               existing_type=sa.VARCHAR(length=150),
               comment='Наименование без формулировок НПА',
               existing_nullable=False)
    op.alter_column('support_measures', 'active',
               existing_type=sa.INTEGER(),
               comment='1 - активна, 0 - убрать с платформы',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('support_measures', 'id_form',
               existing_type=sa.VARCHAR(),
               comment='ID формы предоставления (0 если универсальная)',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::character varying"))
    op.alter_column('support_measures', 'id',
               existing_type=sa.VARCHAR(),
               comment='Внутренний ID меры поддержки',
               existing_comment='Внутренний ID',
               existing_nullable=False)
    op.drop_column('support_measures', 'source_url')
    op.drop_column('support_measures', 'source_name')
    op.drop_column('support_measures', 'recipient_description')
    # ### end Alembic commands ###
