"""Init database schema

Revision ID: d44029bc4885
Revises: 
Create Date: 2026-09-26 22:00:21.809909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd44029bc4885'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'inn',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='ИНН компании (моковые данные)',
               existing_nullable=False)
    op.alter_column('companies', 'name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Название ООО/ИП',
               existing_nullable=False)
    op.alter_column('companies', 'opf',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='ОПФ компании',
               existing_nullable=False)
    op.alter_column('companies', 'okwed',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Основной ОКВЭД',
               existing_nullable=False)
    op.alter_column('companies', 'employees_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Кол-во сотрудников',
               existing_nullable=True)
    op.alter_column('companies', 'exist_term_months',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Возраст бизнеса (мес)',
               existing_nullable=True)
    op.alter_column('companies', 'region_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Ссылка на регион (ОКАТО)',
               existing_nullable=False)
    op.drop_constraint(op.f('companies_region_id_fkey'), 'companies', type_='foreignkey')
    op.create_foreign_key(None, 'companies', 'regions', ['region_id'], ['id'])
    op.alter_column('documents', 'measure_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Связь многие-к-одному',
               existing_nullable=False)
    op.alter_column('documents', 'link',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Ссылка на документ на внешнем ресурсе',
               existing_nullable=False)
    op.alter_column('documents', 'type',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Формат: pdf, docx, jpg',
               existing_nullable=True)
    op.alter_column('documents', 'size',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Размер в килобайтах',
               existing_nullable=True)
    op.alter_column('documents', 'name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Имя документа с реквизитами',
               existing_nullable=False)
    op.alter_column('documents', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Описание',
               existing_nullable=True)
    op.alter_column('measure_requirements', 'measure_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Связь 1 к 1 с мерой поддержки',
               existing_nullable=False)
    op.alter_column('measure_requirements', 'opf',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='ОПФ: individual, legal, self и т.д. (массив)',
               existing_nullable=True)
    op.alter_column('measure_requirements', 'okwed',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Допустимые ОКВЭДы (массив)',
               existing_nullable=True)
    op.alter_column('measure_requirements', 'not_okwed',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Недопустимые ОКВЭДы (массив)',
               existing_nullable=True)
    op.alter_column('measure_requirements', 'min_empl_amount',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Мин. кол-во сотрудников',
               existing_nullable=True)
    op.alter_column('measure_requirements', 'max_empl_amount',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Макс. кол-во сотрудников',
               existing_nullable=True)
    op.alter_column('measure_requirements', 'min_exist_term',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Мин. срок ведения бизнеса (в месяцах)',
               existing_nullable=True)
    op.alter_column('measure_requirements', 'okato',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Ограничения по ОКАТО (0 - вся РФ)',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::character varying"))
    op.alter_column('measure_requirements', 'ukep',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Требование наличия УКЭП (ЭЦП)',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('measure_requirements', 'scoring',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Требование прохождения скоринга',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('regions', 'okato',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Код ОКАТО (например 01)',
               existing_nullable=False)
    op.alter_column('regions', 'code',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='ISO код (например RU-ALT)',
               existing_nullable=False)
    op.alter_column('regions', 'name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Название региона',
               existing_nullable=False)
    op.alter_column('regions', 'district',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Федеральный округ',
               existing_nullable=True)
    op.alter_column('support_measures', 'id_form',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='ID формы предоставления (0 если универсальная)',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::character varying"))
    op.alter_column('support_measures', 'active',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='1 - активна, 0 - убрать с платформы',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('support_measures', 'name',
               existing_type=sa.VARCHAR(length=150),
               comment=None,
               existing_comment='Наименование без формулировок НПА',
               existing_nullable=False)
    op.alter_column('support_measures', 'preview',
               existing_type=sa.VARCHAR(length=250),
               comment=None,
               existing_comment='Краткий анонс для списка',
               existing_nullable=True)
    op.alter_column('support_measures', 'short_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Краткое описание для карточки',
               existing_nullable=True)
    op.alter_column('support_measures', 'full_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Полное описание (с HTML тегами)',
               existing_nullable=True)
    op.alter_column('support_measures', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата начала приема заявок (ISO 8601)',
               existing_nullable=True)
    op.alter_column('support_measures', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата окончания приема заявок (ISO 8601)',
               existing_nullable=True)
    op.alter_column('support_measures', 'support_type',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Форма поддержки (ID из справочника)',
               existing_nullable=True)
    op.alter_column('support_measures', 'support_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Лимит оказания меры на заявителя',
               existing_nullable=True)
    op.alter_column('support_measures', 'support_amount_from',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Размер поддержки ОТ (руб)',
               existing_nullable=True)
    op.alter_column('support_measures', 'support_amount_till',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Размер поддержки ДО (руб)',
               existing_nullable=True)
    op.alter_column('support_measures', 'recipient_category',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Категории: micro, small, medium, other (массив)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('support_measures', 'recipient_category',
               existing_type=sa.VARCHAR(),
               comment='Категории: micro, small, medium, other (массив)',
               existing_nullable=True)
    op.alter_column('support_measures', 'support_amount_till',
               existing_type=sa.INTEGER(),
               comment='Размер поддержки ДО (руб)',
               existing_nullable=True)
    op.alter_column('support_measures', 'support_amount_from',
               existing_type=sa.INTEGER(),
               comment='Размер поддержки ОТ (руб)',
               existing_nullable=True)
    op.alter_column('support_measures', 'support_count',
               existing_type=sa.INTEGER(),
               comment='Лимит оказания меры на заявителя',
               existing_nullable=True)
    op.alter_column('support_measures', 'support_type',
               existing_type=sa.INTEGER(),
               comment='Форма поддержки (ID из справочника)',
               existing_nullable=True)
    op.alter_column('support_measures', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата окончания приема заявок (ISO 8601)',
               existing_nullable=True)
    op.alter_column('support_measures', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата начала приема заявок (ISO 8601)',
               existing_nullable=True)
    op.alter_column('support_measures', 'full_description',
               existing_type=sa.TEXT(),
               comment='Полное описание (с HTML тегами)',
               existing_nullable=True)
    op.alter_column('support_measures', 'short_description',
               existing_type=sa.TEXT(),
               comment='Краткое описание для карточки',
               existing_nullable=True)
    op.alter_column('support_measures', 'preview',
               existing_type=sa.VARCHAR(length=250),
               comment='Краткий анонс для списка',
               existing_nullable=True)
    op.alter_column('support_measures', 'name',
               existing_type=sa.VARCHAR(length=150),
               comment='Наименование без формулировок НПА',
               existing_nullable=False)
    op.alter_column('support_measures', 'active',
               existing_type=sa.INTEGER(),
               comment='1 - активна, 0 - убрать с платформы',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('support_measures', 'id_form',
               existing_type=sa.VARCHAR(),
               comment='ID формы предоставления (0 если универсальная)',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::character varying"))
    op.alter_column('regions', 'district',
               existing_type=sa.VARCHAR(),
               comment='Федеральный округ',
               existing_nullable=True)
    op.alter_column('regions', 'name',
               existing_type=sa.VARCHAR(),
               comment='Название региона',
               existing_nullable=False)
    op.alter_column('regions', 'code',
               existing_type=sa.VARCHAR(length=10),
               comment='ISO код (например RU-ALT)',
               existing_nullable=False)
    op.alter_column('regions', 'okato',
               existing_type=sa.VARCHAR(length=20),
               comment='Код ОКАТО (например 01)',
               existing_nullable=False)
    op.alter_column('measure_requirements', 'scoring',
               existing_type=sa.BOOLEAN(),
               comment='Требование прохождения скоринга',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('measure_requirements', 'ukep',
               existing_type=sa.BOOLEAN(),
               comment='Требование наличия УКЭП (ЭЦП)',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('measure_requirements', 'okato',
               existing_type=sa.VARCHAR(),
               comment='Ограничения по ОКАТО (0 - вся РФ)',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::character varying"))
    op.alter_column('measure_requirements', 'min_exist_term',
               existing_type=sa.INTEGER(),
               comment='Мин. срок ведения бизнеса (в месяцах)',
               existing_nullable=True)
    op.alter_column('measure_requirements', 'max_empl_amount',
               existing_type=sa.INTEGER(),
               comment='Макс. кол-во сотрудников',
               existing_nullable=True)
    op.alter_column('measure_requirements', 'min_empl_amount',
               existing_type=sa.INTEGER(),
               comment='Мин. кол-во сотрудников',
               existing_nullable=True)
    op.alter_column('measure_requirements', 'not_okwed',
               existing_type=sa.VARCHAR(),
               comment='Недопустимые ОКВЭДы (массив)',
               existing_nullable=True)
    op.alter_column('measure_requirements', 'okwed',
               existing_type=sa.VARCHAR(),
               comment='Допустимые ОКВЭДы (массив)',
               existing_nullable=True)
    op.alter_column('measure_requirements', 'opf',
               existing_type=sa.VARCHAR(),
               comment='ОПФ: individual, legal, self и т.д. (массив)',
               existing_nullable=True)
    op.alter_column('measure_requirements', 'measure_id',
               existing_type=sa.VARCHAR(),
               comment='Связь 1 к 1 с мерой поддержки',
               existing_nullable=False)
    op.alter_column('documents', 'description',
               existing_type=sa.TEXT(),
               comment='Описание',
               existing_nullable=True)
    op.alter_column('documents', 'name',
               existing_type=sa.VARCHAR(),
               comment='Имя документа с реквизитами',
               existing_nullable=False)
    op.alter_column('documents', 'size',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Размер в килобайтах',
               existing_nullable=True)
    op.alter_column('documents', 'type',
               existing_type=sa.VARCHAR(length=10),
               comment='Формат: pdf, docx, jpg',
               existing_nullable=True)
    op.alter_column('documents', 'link',
               existing_type=sa.VARCHAR(),
               comment='Ссылка на документ на внешнем ресурсе',
               existing_nullable=False)
    op.alter_column('documents', 'measure_id',
               existing_type=sa.VARCHAR(),
               comment='Связь многие-к-одному',
               existing_nullable=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.create_foreign_key(op.f('companies_region_id_fkey'), 'companies', 'regions', ['region_id'], ['id'], deferrable=True)
    op.alter_column('companies', 'region_id',
               existing_type=sa.INTEGER(),
               comment='Ссылка на регион (ОКАТО)',
               existing_nullable=False)
    op.alter_column('companies', 'exist_term_months',
               existing_type=sa.INTEGER(),
               comment='Возраст бизнеса (мес)',
               existing_nullable=True)
    op.alter_column('companies', 'employees_count',
               existing_type=sa.INTEGER(),
               comment='Кол-во сотрудников',
               existing_nullable=True)
    op.alter_column('companies', 'okwed',
               existing_type=sa.VARCHAR(length=10),
               comment='Основной ОКВЭД',
               existing_nullable=False)
    op.alter_column('companies', 'opf',
               existing_type=sa.VARCHAR(),
               comment='ОПФ компании',
               existing_nullable=False)
    op.alter_column('companies', 'name',
               existing_type=sa.VARCHAR(),
               comment='Название ООО/ИП',
               existing_nullable=False)
    op.alter_column('companies', 'inn',
               existing_type=sa.VARCHAR(length=12),
               comment='ИНН компании (моковые данные)',
               existing_nullable=False)
    # ### end Alembic commands ###
